using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Api.Models;

namespace Api.Data.Configurations;

public abstract class BaseEntityConfiguration<T> : IEntityTypeConfiguration<T> where T : BaseEntity
{
  public virtual void Configure(EntityTypeBuilder<T> builder)
  {
    builder.HasKey(e => e.Id);

    builder.Property(e => e.Id)
        .IsRequired()
        .ValueGeneratedOnAdd();  // Auto-increment, generated by database

    builder.Property(e => e.CreatedAt)
        .IsRequired();
  }
}